server:
    port: 8888

# Spring配置
spring:
    jackson:
        date-format: 'yyyy-MM-dd HH:mm:ss'
        time-zone: 'GMT+8'
        mapper:
            # 格式化JSON按照字典顺序排序
            sort-properties-alphabetically: true
    config:
        use-legacy-processing: true
    main:
        allow-circular-references: true
    profiles:
        active: dev

#mybatis-plus:
#  configuration:
#    cache-enabled: false
